# makefile for hexdump program
# g++ compiler
CXX=g++
# flags
CXXFLAGS=-std=c++11 -g
# target with output of dbx executable
dxe: dxe.cpp
	$(CXX) $(CXXFLAGS) -o dxe dxe.cpp

# call clean to remove executable
clean:
	rm dxe
